# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-23 15:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_app', '0003_auto_20171023_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quoteby', models.CharField(max_length=45)),
                ('quotetext', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('postedby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_quotes', to='login_app.User')),
            ],
        ),
    ]
