# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-23 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0003_auto_20171023_1457'),
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='favoritedby',
            field=models.ManyToManyField(default=None, related_name='favorites', to='login_app.User'),
        ),
    ]
