# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-23 14:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0002_auto_20171019_1620'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='first',
            new_name='alias',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='last',
            new_name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='bday',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
